-- MySQL Script generated by MySQL Workbench
-- 12/17/16 22:47:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reminder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reminder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reminder` DEFAULT CHARACTER SET utf8 ;
USE `reminder` ;

-- -----------------------------------------------------
-- Table `reminder`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reminder`.`users` (
  `idusers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reminder`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reminder`.`items` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `user` INT NOT NULL,
  `done` TINYINT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
